#include "commons/DigitalInputPin.h"
#include "commons/DigitalOutputPin.h"
#include "commons/AnalogInputPin.h"
#include "buttons/SwitchButton.h"
#include "lights/DiodeLed.h"
#include "lights/LightDependentResistor.h"
#include "switchs/Relay.h"